### ISSUE TITLE
Spark: Hands-On Tour of Spark can't run Notebook

### ISSUE THREAD

**Issue by rjzak** [hortonworks/data-tutorials#786]
**Tutorial name**: Hands-On Tour of Apache Spark in 5 Minutes
**Platform version**: HDP 3.0.1 181205 VirtualBox
**Link to tutorial**: https://hortonworks.com/tutorial/hands-on-tour-of-apache-spark-in-5-minutes/
Notebook: https://raw.githubusercontent.com/hortonworks/data-tutorials/master/tutorials/hdp/hands-on-tour-of-apache-spark-in-5-minutes/assets/Getting%20Started%20_%20Apache%20Spark%20in%205%20Minutes.json

### Description of issue:
Trying to run the second paragraph in the Zeppelin notebook:
`%sh`
`if [ -e /tmp/svepisodes.json ] #  Remove old json file if already exists in local /tmp directory`
`then`
    `rm -f /tmp/svepisodes.json`
`fi`
`wget https://raw.githubusercontent.com/hortonworks/data-tutorials/master/tutorials/hdp/hands-on-tour-of-apache-spark-in-5-minutes/assets/svepisodes.json -O /tmp/svepisodes.json -O /tmp/svepisodes.json`

Yields error:
`org.apache.zeppelin.interpreter.InterpreterNotFoundException: Either no interpreter named sh or it is not binded to this note
	at org.apache.zeppelin.interpreter.InterpreterFactory.getInterpreter(InterpreterFactory.java:101)
	at org.apache.zeppelin.notebook.Paragraph.getBindedInterpreter(Paragraph.java:242)
	at org.apache.zeppelin.notebook.Paragraph.execute(Paragraph.java:350)
	at org.apache.zeppelin.notebook.Note.run(Note.java:683)
	at org.apache.zeppelin.socket.NotebookServer.persistAndExecuteSingleParagraph(NotebookServer.java:1867)
	at org.apache.zeppelin.socket.NotebookServer.runParagraph(NotebookServer.java:1826)
	at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:261)
	at org.apache.zeppelin.socket.NotebookSocket.onWebSocketText(NotebookSocket.java:59)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189)
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:476)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:183)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:245)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)`

### Proposed fix (if any):

- Create the config to add the `sh` interpreter for Zeppelin in the HDP image, or
- Add wording to the tutorial to instruct the user to add the interpreter.

**Comment by LopezChris** [comment]
Hello,

The Hands-On Tour of Apache Spark in 5 Minutes tutorial indicates in the [prerequisites](https://hortonworks.com/tutorial/hands-on-tour-of-apache-spark-in-5-minutes/#prerequisites) section that the shell interpreter is needed to complete the tutorial. The link on the prerequites section will redirect you to the [binding an interpreter](https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/#binding-an-interpreter) section of [Getting Started with Apache Zeppelin](https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/) tutorial where the shell interpreter is used as an example.

This should address the error message you have encountered. Please let us know if further issues arise after binding the shell interpreter to your Zeppelin notebook, I will close this issue for now as I do not see further issues.

Thank you.
